apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/kmozafari/polar-book-shop/dispatcher-service/k8s?ref=main


configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: dispatcher-config
images:
- name: dispatcher-service
  newName: ghcr.io/kmozafari/dispatcher-service
  newTag: latest

replicas:
- count: 1
  name: dispatcher-service
patches:
- path: patch-env.yml
- path: patch-volumes.yml
- path: patch-resources.yml
