include('../../../../PolarBookshop/catalog-service/Tiltfile')
include('../../../../PolarBookshop/config-service/Tiltfile')
include('../../../../PolarBookshop/order-service/Tiltfile')
include('../../../../PolarBookshop/edge-service/Tiltfile')
include('../../../../PolarBookshop/dispatcher-service/Tiltfile')

update_settings(max_parallel_updates=1)
