apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/kmozafari/polar-book-shop/edge-service/k8s?ref=main


configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: edge-config
images:
- name: edge-service
  newName: ghcr.io/kmozafari/edge-service
  newTag: a19241536c0af3ed41d9710dc811b3b099ee114e

replicas:
- count: 1
  name: edge-service
patches:
- path: patch-env.yml
- path: patch-volumes.yml
- path: patch-resources.yml
- path: patch-ingress.yml
